imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    # The 'ide' option turns all of the file paths in an exception page
    # into clickable links that open the given file using your favorite IDE.
    # Supported values are 'phpstorm', 'sublime', 'textmate', 'macvim' and 'emacs'.
    # When 'ide' is set to null the file is opened in your web browser.
    # See http://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: '%kernel.debug%'
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%env(SYMFONY_LOG)%"
            level:  info
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

swiftmailer:
    disable_delivery:  true
