imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%env(SYMFONY_LOG)%"
            level:  info
        console:
            type:   console
            bubble: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        path:   "%kernel.root_dir%/../var/data/test.sqlite"
