imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Basic configuration for the Symfony framework features
framework:
    translator:      { fallback: "%locale%" }
    secret:          "%env(SYMFONY_SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
            enabled: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: false
    assets: ~

# Doctrine Configuration (used to access databases and manipulate their information)
doctrine:
    dbal:
         driver:   pdo_mysql
         host:     "%database_host%"
         port:     "%database_port%"
         dbname:   "%database_name%"
         user:     "%database_user%"
         password: "%database_password%"
         charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration (used to send emails)
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig
    templating: false
    default_renderer: twig

mopa_bootstrap:
    form: ~
    menu: ~

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
            address: you@example.com
            sender_name: You

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:        [ AppBundle, MopaBootstrapBundle ]
    filters:
        cssrewrite: ~
        lessphp:
           file: "%kernel.root_dir%/../vendor/oyejorge/less.php/lessc.inc.php"

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: 'Admin'
