root:
   path: /
   defaults:
       _controller: AppBundle:Default:redirect

app:
    resource: '@AppBundle/Controller/'
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: %app_locales%

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /{_locale}/admin
    requirements:
        _locale: %app_locales%

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin/user